export const GET_PRODUCTS = "GET_PRODUCTS";

export const ADD_CART = "ADD_CART";
export const GET_CART_NUMBER = "GET_CART_NUMBER";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
export const CLEAR_PRODUCT = "CLEAR_PRODUCT";
export const CLEAR_CART = "CLEAR_CART";
//Current User Info
export const ADD_CURRENT_USER = "ADD_CURRENT_USER";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_ERROR = "ADD_USER_ERROR";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";
export const SELECT_CATEGORY = "SELECT_CATEGORY";
// export const EDIT_CURRENT_USER = 'EDIT_CURRENT_USER';
// export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
// export const EDIT_USER_ERROR = 'EDIT_USER_ERROR';
// export const DELETE_USER_INFO = 'DELETE_USER_INFO';
// export const DELETE_INFO_SUCCESS = 'DELETE_INFO_SUCCESS';
// export const DELETE_INFO_ERROR = 'DELETE_INFO_ERROR';
